"""
Excel Workbook Manager.
Creates fresh workbooks for each survey analysis.
Each survey generates a unique workbook - no static templates.
"""

from pathlib import Path
from typing import Optional, List, Dict, Any
from datetime import datetime

from openpyxl import load_workbook, Workbook
from openpyxl.worksheet.worksheet import Worksheet
from openpyxl.utils import get_column_letter


class ExcelWorkbookManager:
    """
    Creates and manages Excel workbooks for survey analysis.
    Each survey gets a fresh workbook with dynamic content.
    """

    def __init__(self):
        """Initialize the workbook manager."""
        self.workbook: Optional[Workbook] = None
        self.output_path: Optional[Path] = None

    def create_workbook(
        self,
        output_path: Path,
        session_id: str
    ) -> Workbook:
        """
        Create a fresh workbook for this analysis session.

        Args:
            output_path: Path for the output .xlsx file.
            session_id: Session identifier for tracking.

        Returns:
            New Workbook instance.
        """
        self.workbook = Workbook()
        self.output_path = output_path.with_suffix('.xlsx')

        if "Sheet" in self.workbook.sheetnames:
            del self.workbook["Sheet"]

        self._add_metadata_sheet(session_id)

        return self.workbook

    def load_existing_workbook(self, workbook_path: Path) -> Workbook:
        """
        Load an existing macro-enabled workbook.

        Args:
            workbook_path: Path to existing .xlsm file.

        Returns:
            Workbook instance with VBA preserved.
        """
        keep_vba = workbook_path.suffix.lower() == '.xlsm'
        self.workbook = load_workbook(workbook_path, keep_vba=keep_vba)
        self.output_path = workbook_path
        return self.workbook

    def _add_metadata_sheet(self, session_id: str) -> None:
        """Add metadata sheet with session info."""
        if self.workbook is None:
            return

        sheet_name = "00_METADATA"
        if sheet_name in self.workbook.sheetnames:
            ws = self.workbook[sheet_name]
        else:
            ws = self.workbook.create_sheet(sheet_name, 0)

        ws["A1"] = "PhD Survey Analysis Workbook"
        ws["A2"] = "Generated by Automated Analysis System"
        ws["A3"] = ""
        ws["A4"] = "Session ID:"
        ws["B4"] = session_id
        ws["A5"] = "Generated:"
        ws["B5"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ws["A6"] = ""
        ws["A7"] = "Computation Method:"
        ws["B7"] = "Excel formulas + Python verification"
        ws["A8"] = ""
        ws["A9"] = "All numeric outputs use Excel formulas referencing raw data."
        ws["A10"] = "Advanced statistics verified against Python ground truth."
        ws["A11"] = "See verification report for statistical accuracy confirmation."

        ws.column_dimensions["A"].width = 50
        ws.column_dimensions["B"].width = 30

    def create_sheet(
        self,
        sheet_name: str,
        position: Optional[int] = None
    ) -> Worksheet:
        """
        Create a new sheet in the workbook.

        Args:
            sheet_name: Name for the new sheet (max 31 chars).
            position: Optional position index for the sheet.

        Returns:
            The created worksheet.

        Raises:
            ValueError: If workbook not initialized or invalid sheet name.
        """
        if self.workbook is None:
            raise ValueError("Workbook not initialized. Call create_workbook_from_template first.")

        safe_name = sanitize_sheet_name(sheet_name)

        if safe_name in self.workbook.sheetnames:
            return self.workbook[safe_name]

        if position is not None:
            ws = self.workbook.create_sheet(safe_name, position)
        else:
            ws = self.workbook.create_sheet(safe_name)

        return ws

    def get_sheet(self, sheet_name: str) -> Optional[Worksheet]:
        """
        Get an existing sheet by name.

        Args:
            sheet_name: Name of the sheet.

        Returns:
            Worksheet if exists, None otherwise.
        """
        if self.workbook is None:
            return None

        safe_name = sanitize_sheet_name(sheet_name)
        if safe_name in self.workbook.sheetnames:
            return self.workbook[safe_name]
        return None

    def save(self, path: Optional[Path] = None) -> Path:
        """
        Save the workbook preserving VBA.

        Args:
            path: Optional output path. Uses original if not specified.

        Returns:
            Path where workbook was saved.

        Raises:
            ValueError: If workbook not initialized.
        """
        if self.workbook is None:
            raise ValueError("Workbook not initialized.")

        save_path = path or self.output_path
        if save_path is None:
            raise ValueError("No output path specified.")

        self.workbook.save(save_path)
        return save_path

    def get_sheet_names(self) -> List[str]:
        """Get list of all sheet names."""
        if self.workbook is None:
            return []
        return self.workbook.sheetnames

    def sheet_exists(self, sheet_name: str) -> bool:
        """Check if a sheet exists."""
        if self.workbook is None:
            return False
        return sanitize_sheet_name(sheet_name) in self.workbook.sheetnames


def sanitize_sheet_name(name: str) -> str:
    """
    Sanitize sheet name for Excel compatibility.

    Args:
        name: Original sheet name.

    Returns:
        Excel-safe sheet name (max 31 chars, no invalid chars).
    """
    invalid_chars = ['\\', '/', '*', '?', ':', '[', ']']
    safe_name = name
    for char in invalid_chars:
        safe_name = safe_name.replace(char, '_')

    safe_name = safe_name[:31]

    return safe_name


def get_column_range(
    start_col: int,
    end_col: int,
    row: int,
    sheet_name: Optional[str] = None
) -> str:
    """
    Generate an Excel range reference.

    Args:
        start_col: Starting column (1-indexed).
        end_col: Ending column (1-indexed).
        row: Row number.
        sheet_name: Optional sheet name for cross-sheet reference.

    Returns:
        Excel range string (e.g., "'Sheet1'!A1:Z1" or "A1:Z1").
    """
    start_letter = get_column_letter(start_col)
    end_letter = get_column_letter(end_col)

    range_str = f"{start_letter}{row}:{end_letter}{row}"

    if sheet_name:
        safe_name = sanitize_sheet_name(sheet_name)
        range_str = f"'{safe_name}'!{range_str}"

    return range_str


def get_cell_reference(
    col: int,
    row: int,
    sheet_name: Optional[str] = None,
    absolute_col: bool = False,
    absolute_row: bool = False
) -> str:
    """
    Generate an Excel cell reference.

    Args:
        col: Column number (1-indexed).
        row: Row number.
        sheet_name: Optional sheet name.
        absolute_col: Use absolute column reference ($A).
        absolute_row: Use absolute row reference ($1).

    Returns:
        Excel cell reference (e.g., "$A$1", "B2", "'Sheet1'!C3").
    """
    col_letter = get_column_letter(col)
    if absolute_col:
        col_letter = f"${col_letter}"
    if absolute_row:
        row_str = f"${row}"
    else:
        row_str = str(row)

    ref = f"{col_letter}{row_str}"

    if sheet_name:
        safe_name = sanitize_sheet_name(sheet_name)
        ref = f"'{safe_name}'!{ref}"

    return ref


def get_data_range(
    sheet_name: str,
    start_col: int,
    start_row: int,
    end_col: int,
    end_row: int
) -> str:
    """
    Generate a rectangular data range reference.

    Args:
        sheet_name: Sheet name.
        start_col: Starting column (1-indexed).
        start_row: Starting row.
        end_col: Ending column (1-indexed).
        end_row: Ending row.

    Returns:
        Excel range string (e.g., "'00_RAW_DATA_LOCKED'!A2:Z100").
    """
    safe_name = sanitize_sheet_name(sheet_name)
    start_letter = get_column_letter(start_col)
    end_letter = get_column_letter(end_col)

    return f"'{safe_name}'!{start_letter}{start_row}:{end_letter}{end_row}"


def create_analysis_workbook(
    output_path: Path,
    session_id: str,
    raw_data_path: Optional[Path] = None
) -> ExcelWorkbookManager:
    """
    Create a fresh analysis workbook for this survey.

    Args:
        output_path: Path for output .xlsx file.
        session_id: Session identifier.
        raw_data_path: Optional path to raw data Excel file.

    Returns:
        Initialized ExcelWorkbookManager with workbook ready.
    """
    manager = ExcelWorkbookManager()
    manager.create_workbook(output_path, session_id)

    if raw_data_path and raw_data_path.exists():
        _copy_raw_data(manager, raw_data_path)

    return manager


def _copy_raw_data(manager: ExcelWorkbookManager, raw_data_path: Path) -> None:
    """
    Copy raw data to the 00_RAW_DATA_LOCKED sheet.

    Args:
        manager: Workbook manager with initialized workbook.
        raw_data_path: Path to source Excel file.
    """
    source_wb = load_workbook(raw_data_path, data_only=True)
    source_ws = source_wb.active

    if source_ws is None:
        source_wb.close()
        return

    dest_ws = manager.create_sheet("00_RAW_DATA_LOCKED", 1)

    for row_idx, row in enumerate(source_ws.iter_rows(values_only=True), 1):
        for col_idx, value in enumerate(row, 1):
            dest_ws.cell(row=row_idx, column=col_idx, value=value)

    source_wb.close()


# Legacy alias for backward compatibility
ExcelTemplateLoader = ExcelWorkbookManager
